name: CI

on:
  push:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Show environment
        env:
          ENVIRONMENT: CI
        run: echo "Running in $ENVIRONMENT"
      
      - name: Use secret
        env:
          DEMO_SECRET: ${{ secrets.CI_DEMO_SECRET }}
        run: echo "Secret is configured $DEMO_SECRET"

      - name: Run test
        run: ./test.sh

      - name: Build Docker image
        run: docker build -t cicd-learning:1.0 .
