name: CI

on:
  push:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Show environment
        env:
          ENVIRONMENT: CI
        run: echo "Running in $ENVIRONMENT"

      - name: Run test
        run: ./test.sh
